openapi: 3.0.0
info:
  title: Bookshelf API
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local Development

paths:
  /books:
    get:
      summary: Ambil semua buku
      responses:
        '200':
          description: OK
    post:
      summary: Tambah buku
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - year
              properties:
                title: { type: string }
                author: { type: string }
                year: { type: integer }
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request - Title atau Year kosong

  /books/search:
    get:
      summary: Mencari buku berdasarkan judul
      parameters:
        - name: title
          in: query
          required: true
          description: Judul buku yang ingin dicari
          schema:
            type: string
      responses:
        '200':
          description: Daftar buku yang cocok ditemukan
        '400':
          description: Parameter title tidak diberikan

  /books/{bookId}:
    parameters:
      - name: bookId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Ambil detail buku berdasarkan ID
      responses:
        '200':
          description: OK
    put:
      summary: Perbarui data buku
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                author: { type: string }
                year: { type: integer }
      responses:
        '200':
          description: Berhasil memperbarui buku
    delete:
      summary: Hapus buku
      responses:
        '200':
          description: Buku berhasil dihapus
